### ISSUE TITLE
[BUG] 1.50.0: "fatal error: concurrent map read and map write"

### ISSUE THREAD

**Issue by drichelson** [DataDog/dd-trace-go#1944]
**Version of dd-trace-go**
1.50.0 (upgrade from 1.48.0 is correlated with this issue)

**Describe what happened:**
fatal error! relevant go routine dump (with internal stacktrace bits elided):
```
"2023-04-26T22:05:11.509Z","fatal error: concurrent map read and map write"
"2023-04-26T22:05:11.509Z","goroutine 101135 [running]:"
"2023-04-26T22:05:11.509Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*propagatorW3c).injectTextMap(0xc03a4f7ad8, {0x45fcad0?, 0xc03ecfc2a0?}, {0x7f8aade2fa60, 0xc03c27d650})"
"2023-04-26T22:05:11.509Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/textmap.go:674 +0x312"
"2023-04-26T22:05:11.509Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*propagatorW3c).Inject(0xc03a4f7ac8?, {0x45fcad0, 0xc03ecfc2a0}, {0x38f1b40?, 0xc03c27d650?})"
"2023-04-26T22:05:11.510Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/textmap.go:630 +0x89"
"2023-04-26T22:05:11.510Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*chainedPropagator).Inject(0xc00007ec00?, {0x45fcad0, 0xc03ecfc2a0}, {0x38f1b40, 0xc03c27d650})"
"2023-04-26T22:05:11.510Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/textmap.go:246 +0x83"
"2023-04-26T22:05:11.510Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).Inject(0xc035b934a0?, {0x45fcad0?, 0xc03ecfc2a0?}, {0x38f1b40?, 0xc03c27d650?})"
"2023-04-26T22:05:11.510Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:595 +0x3f"
"2023-04-26T22:05:11.510Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.Inject({0x45fcad0?, 0xc03ecfc2a0?}, {0x38f1b40?, 0xc03c27d650?})"
"2023-04-26T22:05:11.511Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:180 +0x96"

"2023-04-26T22:05:11.646Z","goroutine 2990 [select]:"
"2023-04-26T22:05:11.646Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*concentrator).runFlusher(...)"
"2023-04-26T22:05:11.646Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:106"
"2023-04-26T22:05:11.646Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*concentrator).Start.func1()"
"2023-04-26T22:05:11.646Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:94 +0x136"
"2023-04-26T22:05:11.646Z","created by gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*concentrator).Start"
"2023-04-26T22:05:11.646Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:90 +0xb8"

"2023-04-26T22:05:11.695Z","goroutine 2989 [select]:"
"2023-04-26T22:05:11.696Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).reportHealthMetrics(0xc014a33900, 0x0?)"
"2023-04-26T22:05:11.696Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/metrics.go:101 +0x1bf"
"2023-04-26T22:05:11.696Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.newTracer.func3()"
"2023-04-26T22:05:11.696Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:277 +0x65"
"2023-04-26T22:05:11.696Z","created by gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.newTracer"
"2023-04-26T22:05:11.696Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:275 +0x196"

"2023-04-26T22:05:11.753Z","goroutine 2991 [select, 8 minutes]:"
"2023-04-26T22:05:11.753Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*concentrator).runIngester(0xc00db600c0)"
"2023-04-26T22:05:11.753Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:127 +0xae"
"2023-04-26T22:05:11.753Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*concentrator).Start.func2()"
"2023-04-26T22:05:11.753Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:99 +0x5a"
"2023-04-26T22:05:11.754Z","created by gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*concentrator).Start"
"2023-04-26T22:05:11.754Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:97 +0x105"

"2023-04-26T22:05:11.829Z","goroutine 2988 [select]:"
"2023-04-26T22:05:11.829Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).worker(0xc014a33900, 0xc00dbf4660)"
"2023-04-26T22:05:11.830Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:310 +0xdc"
"2023-04-26T22:05:11.830Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.newTracer.func2()"
"2023-04-26T22:05:11.830Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:272 +0xba"
"2023-04-26T22:05:11.830Z","created by gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.newTracer"
"2023-04-26T22:05:11.830Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:264 +0x145"

"2023-04-26T22:05:11.891Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).reportRuntimeMetrics(0xc014a33900, 0x2540be400?)"
"2023-04-26T22:05:11.891Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/metrics.go:44 +0x1b3"
"2023-04-26T22:05:11.891Z","gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.newTracer.func1()"
"2023-04-26T22:05:11.891Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:260 +0x68"
"2023-04-26T22:05:11.891Z","created by gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.newTracer"
"2023-04-26T22:05:11.891Z",".../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:258 +0xe5"
```

**Describe what you expected:**
no fatal errors

**Steps to reproduce the issue:**
I'm working on this but I figured the go routine dump + general awareness might be helpful to start.

**Additional environment details (Version of Go, Operating System, etc.):**
running go 1.20.3

**Comment by knusbaum** [comment]
Thanks for this report. We're looking into it.

Is there any `dd-trace-go` code in any of your other stacks? 
Except for `goroutine 101135` here, the rest are sitting in selects, so while I have a good idea of where the read is occuring, I don't see the write in this set of stacks.

**Comment by knusbaum** [comment]
@drichelson 
I've reassessed access to that map, and I believe the PR (#1948) should fix the issue. 

If you have more info on where exactly the race is occurring, that will help us confirm the fix and create a regression test.

**Comment by katiehockman** [comment]
We are preparing the release now and I expect it to be published within the next 24-48 hours. Thanks for the message.

**Comment by katiehockman** [comment]
v1.50.1 has been released which included the fix for this bug. It would be helpful if you could confirm that upgrading fixes the issue for you.
Thanks again for reporting the issue and for the details you provided.

**Comment by phoenix2x** [comment]
Confirming that the new version fixes our issues. Thank you for the quick turnaround.
