### ISSUE TITLE
[BUG] Fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by FilipNikolovski** [DataDog/dd-trace-go#2089]
When using an http client wrapped with the datadog `WrapClient` function, there is a panic when using the client to make requests in multiple goroutines:

```
external/io_opencensus_go/stats/view/worker.go:34 +0x8d
created by go.opencensus.io/stats/view.init.0
external/io_opencensus_go/stats/view/worker.go:276 +0xad
go.opencensus.io/stats/view.(*worker).start(0xc0004de100)
goroutine 9 [select]:
GOROOT/src/net/http/transport.go:1752 +0x1791
created by net/http.(*Transport).dialConn
GOROOT/src/net/http/transport.go:2392 +0xf5
net/http.(*persistConn).writeLoop(0xc0027dd320)
goroutine 3280 [select, 739 minutes]:
hooks/cmd/eventpush/main.go:66 +0x2a5
main.main()
amqp/amqp.go:350 +0x2e8
github.com/<redacted>/src/amqp.(*Consumer).HandleMessages(0xc0004de200, {0x124cb60?, 0xc0001133c0?}, 0x19c81a0?, 0xc001518750)
goroutine 1 [chan receive]:
hooks/cmd/eventpush/main.go:100 +0xbbb
created by main.makeHandler.func1
hooks/cmd/eventpush/main.go:110 +0x3c5
main.makeHandler.func1.1({{0xc006d0a3f0, 0x24}, 0xe096, {0xc0059c8cf0, 0x11}, {0xc00020a5a0, 0x1d3, 0x1e0}}, {0xc004d6f540, 0x39}, ...)
hooks/pkg/services/eventpusher.go:65 +0x78c
github.com/<redacted>/src/hooks/pkg/services.(*HttpClientImpl).PushEvent(0xc00669c3c0?, {0x124b4a0, 0xc004942450}, {{0xc006d0a3f0, 0x24}, 0xe096, {0xc0059c8cf0, 0x11}, {0xc00020a5a0, 0x1d3, ...}}, ...)
GOROOT/src/net/http/client.go:581
net/http.(*Client).Do(...)
GOROOT/src/net/http/client.go:715 +0x8fc
net/http.(*Client).do(0xc004943cb0, 0xc0053b5600)
GOROOT/src/net/http/client.go:175 +0x9b
net/http.(*Client).send(0xc004943cb0, 0xc0053b5600, {0x100000000?, 0x0?, 0x0?})
GOROOT/src/net/http/client.go:251 +0x5f7
net/http.send(0xc0053b5600, {0x1245940, 0xc0005b3320}, {0xef0420?, 0xa77e8854ecc30001?, 0x0?})
external/in_gopkg_datadog_dd_trace_go_v1/contrib/net/http/roundtripper.go:67 +0x870
gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http.(*roundTripper).RoundTrip(0xc0005b3320, 0xc0053b5600)
external/in_gopkg_datadog_dd_trace_go_v1/ddtrace/tracer/tracer.go:180 +0x96
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.Inject({0x124a5e8?, 0xc004862700?}, {0xe2a5a0?, 0xc0046021e0?})
external/in_gopkg_datadog_dd_trace_go_v1/ddtrace/tracer/tracer.go:595 +0x3f
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).Inject(0xc0059aeb00?, {0x124a5e8?, 0xc004862700?}, {0xe2a5a0?, 0xc0046021e0?})
external/in_gopkg_datadog_dd_trace_go_v1/ddtrace/tracer/textmap.go:246 +0xa2
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*chainedPropagator).Inject(0xc00683cbc0?, {0x124a5e8, 0xc004862700}, {0xe2a5a0, 0xc0046021e0})
external/in_gopkg_datadog_dd_trace_go_v1/ddtrace/tracer/textmap.go:630 +0x89
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*propagatorW3c).Inject(0xc?, {0x124a5e8, 0xc004862700}, {0xe2a5a0?, 0xc0046021e0?})
external/in_gopkg_datadog_dd_trace_go_v1/ddtrace/tracer/textmap.go:675 +0x368
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*propagatorW3c).injectTextMap(0x30, {0x124a5e8?, 0xc004862700?}, {0x7ff603b1f248, 0xc0046021e0})
goroutine 26052 [running]:
fatal error: concurrent map read and map write
```

**Version of dd-trace-go**
v1.50.0

**Describe what you expected:**

The application not to panic.

**Steps to reproduce the issue:**

1. We have an RMQ consumer that listens on incoming messages and processes each message in a separate goroutine, something like:

```go
func (c *Consumer) HandleMessages(
	ctx context.Context,
	deliveries <-chan amqp.Delivery,
	fn Handler,
) {
	ctx, cancel := context.WithCancel(ctx)

	g := new(errgroup.Group)

	g.Go(func() error {
		<-ctx.Done()

		return c.Shutdown()
	})

	g.Go(func() error {
		<-c.done
		cancel()

		return nil
	})

	newFn := func(ctx context.Context, d amqp.Delivery, pub AMQPPublisher) func() error {
		return func() error {
			select {
			default:
			case <-ctx.Done():
				return nil
			}

			reqID := ExtractRequestIDFromHeader(d.Headers)

			sctx, err := tracer.Extract(NewHeaderCarrier(d.Headers))
			if err != nil {
				logger.From(ctx).WithError(err).Warn("unable to extract span from amqp header, starting a fresh span")
			}

			span := tracer.StartSpan(
				c.bindingKey,
				tracer.ChildOf(sctx),
				tracer.ResourceName("handleDelivery"), // resource name
				tracer.SpanType("amqp.delivery"),
				tracer.Tag("exchange", c.exchange),
				tracer.Tag("request_id", reqID),
			)

			ctx = ctxnocancel.Context(NewContext(ctx, reqID))

			// add the span data to the context
			ctx = tracer.ContextWithSpan(ctx, span)

			err = fn(ctx, d, pub)

			// finish with errors
			var finishOptions []tracer.FinishOption
			if err != nil {
				finishOptions = []tracer.FinishOption{tracer.WithError(err)}
			}

			span.Finish(finishOptions...)

			return nil
		}
	}

	for d := range deliveries {
		g.Go(newFn(ctx, d, c.Channel))
	}

	if err := g.Wait(); err != nil && !errors.Is(err, ErrChannelClosed) {
		log.Errorf("Error during shutdown: %s", err)
	}
```

The HandleMessages method takes a delivery channel (opened beforehand) and is invoked once in `main.go` and blocks until the connection is shutdown.

2. Inside the Handler function we have an http client wrapped using `ddhttp.WrapClient`, that makes HTTP requests, in separate goroutines, for each URL included in the message body. We wait on all goroutines to finish before acknowledging each message.

**Comment by FilipNikolovski** [comment]
Seeing as this is fixed in v1.51.0 I'm closing this issue.
