### ISSUE TITLE
HTTP Error 500 from DD setTagError 

### ISSUE THREAD

**Issue by micrump** [DataDog/dd-trace-go#851]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/60554141/108377167-0a1c6200-7204-11eb-8828-75c46b22c9ef.png">

````
*errors.errorString: 500: Internal Server Error
goroutine 201680430 [running]:
runtime/debug.Stack(0xa257e0, 0xc000c28240, 0xaf3aa7)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*span).setTagError(0xc0009828f0, 0xa28be0, 0xc0008c0df0, 0xc000ca5a88)
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.24.1/ddtrace/tracer/span.go:143 +0x745
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*span).SetTag(0xc0009828f0, 0xaef4ac, 0x5, 0xa28be0, 0xc0008c0df0)
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.24.1/ddtrace/tracer/span.go:102 +0x749
gopkg.in/DataDog/dd-trace-go.v1/contrib/go-chi/chi.Middleware.func1.1(0xbe55c0, 0xc000986380, 0xc00046d700)
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.24.1/contrib/go-chi/chi/chi.go:68 +0x8ea
net/http.HandlerFunc.ServeHTTP(0xc00082f6e0, 0xbe55c0, 0xc000986380, 0xc00046d700)
/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000255b60, 0xbe55c0, 0xc000986380, 0xc00046d600)
/go/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:81 +0x294
net/http.serverHandler.ServeHTTP(0xc00013e4e0, 0xbe55c0, 0xc000986380, 0xc00046d600)
/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0008ed540, 0xbe7080, 0xc0011da9c0)
/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:2884 +0x2f4
````
There seems to be an issue with the Go Datadog integration. This causes our gateway to return a HTTP 500 instead of a 200 that it receives from a downstream microservice.

**Comment by gbbr** [comment]
I realise how this can be misleading at times. That line will show up in all stack trace reports, because it is the tracer which reports the error and records the stack, without excluding itself from the stack report. As you can see the immediate next call is to `debug.Stack`.

This is not an issue.

I am going to close, but feel free to write more information if you feel otherwise and I'm happy to continue discussing and even potentially re-opening the issue if needed.
